### ISSUE TITLE
i have Exception can you help me 

### ISSUE THREAD

**Issue by bayanJarour20** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#20]
i have this exception https://code.djangoproject.com/ticket/30500 how i can solve it ?

**Comment by Vcd2002** [comment]
bro did you solved it i have the same problem

**Comment by ninjawarr** [comment]
> bro did you solved it i have the same problem

Did you solved the problem i am strucked with this problem

**Comment by ninjawarr** [comment]
> i install the project and i am trying run the django application and i install python v3.6 and django v3.0 but i have this exception when i write python manage.py runserver: Exception in thread django-main-thread: Traceback (most recent call last): File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\urls\resolvers.py", line 589, in url_patterns iter(patterns) TypeError: 'module' object is not iterable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\OSAMA\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner self.run() File "C:\Users\OSAMA\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run self._target(*self._args, **self._kwargs) File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper fn(*args, **kwargs) File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run self.check(display_num_errors=True) File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\core\management\base.py", line 395, in check include_deployment_checks=include_deployment_checks, File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\core\management\base.py", line 382, in _run_checks return checks.run_checks(**kwargs) File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks new_errors = check(app_configs=app_configs) File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config return check_resolver(resolver) File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver return check_method() File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\urls\resolvers.py", line 406, in check for pattern in self.url_patterns: File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\utils\functional.py", line 48, in **get** res = instance.**dict**[self.name] = self.func(instance) File "C:\Deepfake_detection_using_deep_learning\Django Application\venv\lib\site-packages\django\urls\resolvers.py", line 596, in url_patterns raise ImproperlyConfigured(msg.format(name=self.urlconf_name)) django.core.exceptions.ImproperlyConfigured: The included URLconf 'project_settings.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import. how i can solve it?

Bro did you resolved the eroor
