### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/app/models'

### ISSUE THREAD

**Issue by chaukegunjan6969** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#24]
=> ERROR [stage-1 10/12] RUN python manage.py collectstatic --noinput                                                                                     1.5s
------
 > [stage-1 10/12] RUN python manage.py collectstatic --noinput:
1.353 Traceback (most recent call last):
1.353   File "manage.py", line 21, in <module>
1.353     main()
1.353   File "manage.py", line 17, in main
1.353     execute_from_command_line(sys.argv)
1.353   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
1.353     utility.execute()
1.353   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
1.353     self.fetch_command(subcommand).run_from_argv(self.argv)
1.353   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
1.354     self.execute(*args, **cmd_options)
1.354   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
1.354     output = self.handle(*args, **options)
1.354   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
1.354     collected = self.collect()
1.354   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 104, in collect
1.354     for path, storage in finder.list(self.ignore_patterns):
1.354   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 130, in list
1.355     for path in utils.get_files(storage, ignore_patterns):
1.355   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
1.355     directories, files = storage.listdir(location)
1.355   File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 316, in listdir
1.355     for entry in os.scandir(path):
1.355 FileNotFoundError: [Errno 2] No such file or directory: '/app/models'
------
Dockerfile:17
--------------------
  15 |     RUN pip install -r requirements.txt
  16 |     COPY . /app
  17 | >>> RUN python manage.py collectstatic --noinput
  18 |
  19 |     RUN pip install gunicorn

**Comment by papapizzachess** [comment]
Any updates on this? I am having the same issue.
