### ISSUE TITLE
  ERROR: Failed building wheel for dlib Failed to build dlib ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by DEEPAKM-1872003** [abhijitjadhav1998/Deepfake_detection_using_deep_learning#28]
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "D:\Finalyearproject\Deepfake_detection_using_deep_learning\Django Application\venv\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "D:\Finalyearproject\Deepfake_detection_using_deep_learning\Django Application\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Finalyearproject\Deepfake_detection_using_deep_learning\Django Application\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Finalyearproject\Deepfake_detection_using_deep_learning\Django Application\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 223, in <module>
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Deepak\AppData\Local\Temp\pip-build-env-x1s8c8n7\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 129, in run
        File "<string>", line 120, in get_cmake_version
        File "C:\Users\Deepak\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Deepak\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: Could not build wheels for dlib, which is required to install pyproject.toml-based projects

(venv) D:\Finalyearproject\Deepfake_detection_using_deep_learning\Django Application>python setup.py install --no dlib_if_support
C:\Users\Deepak\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\Finalyearproject\\Deepfake_detection_using_deep_learning\\Django Application\\setup.py': [Errno 2] No such file or directory

(venv) D:\Finalyearproject\Deepfake_detection_using_deep_learning\Django Application>python setup.py install --no dlib_s
upport
C:\Users\Deepak\AppData\Local\Programs\Python\Python311\python.exe: can't open file 'D:\\Finalyearproject\\Deepfake_detection_using_deep_learning\\Django Application\\setup.py': [Errno 2] No such file or directory

**Comment by DEEPAKM-1872003** [comment]
couldn't able to finish those requirements step, what to do , need solution

**Comment by SanchitDua20** [comment]
> couldn't able to finish those requirements step, what to do , need solution

Hey, 
Is there any update?
I'm stuck because of this same issue.

**Comment by DEEPAKM-1872003** [comment]
Bro just delete the clones repository and clone it again then re install all requirement , also generalize the requirements version like instead of torch==1.9.0 . Try like torch =>1.9.0 , because of different dependency

**Comment by SanchitDua20** [comment]
Is it possible for you to connect over discord or google meet. I value your
time and efforts but we are preparing this as out major project and we need
to clear all these issues before the deadline.
I really appreciate your efforts.
Thank you

**Comment by SanchitDua20** [comment]
> Bro just delete the clones repository and clone it again then re install all requirement , also generalize the requirements version like instead of torch==1.9.0 . Try like torch =>1.9.0 , because of different dependency

![Uploading IMG20240520201356.jpg…]()

**Comment by sumanth2002** [comment]
install the dlib from the github [https://github.com/z-mahmud22/Dlib_Windows_Python3.x] this should solve your problem
